#cc = gcc 
all:
	
	gcc  tcpsend01.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o send01 
	gcc  tcprecv01.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o recv01
	gcc  tcprecv02.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o recv02


