#cc = gcc 
all:
	
	gcc  tcpsend01.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o cli 
	gcc  tcprecv01.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o ser


