#cc = gcc 
all:
	
	#gcc  tcpsend01.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o send01 
	#gcc  tcprecv01.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o recv01
	#gcc  tcprecv02.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o recv02
	#gcc  tcpsend04.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o send04
	#gcc  tcprecv04.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o recv04
	#gcc  tcpsend05.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o send05
	#gcc  tcprecv05.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o recv05
	gcc -g  cli_main.c heartbeat_cli.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o heart_cli
	gcc -g serv_main.c heartbeat_serv.c /home/Shengxi-Liu/unix_network_progream_code/liushengxi_code/chilrd/*.c -o heart_serv